project:
  type: website
  output-dir: _site
  render:
    - "**/*.qmd"
    - "notebooks/*.Rmd"

website:
  title: "Machine Learning Summer School 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: curriculum-outline.qmd
        text: Curriculum
      - href: slides/day-01-monday.qmd
        text: Monday
      - href: slides/day-02-tuesday.qmd
        text: Tuesday
      - href: slides/day-03-thursday.qmd
        text: Thursday
      - href: modules/index.qmd
        text: Modules
      - text: Notebooks
        menu:
          - text: Student notebooks
            href: notebooks/index.qmd
          - text: Linear regression + LASSO
            href: notebooks/linear-regression-lasso.Rmd
          - text: Logistic regression + tree
            href: notebooks/logistic-regression-gene-disease.Rmd

format:
  html:
    theme: solar
    toc: true
    css: assets/css/hub.css

execute:
  freeze: auto
